name: Python CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Set up Virtual Environment
      run: |
        python -m venv env
        source env/bin/activate
    - name: Install Dependencies
      run: |
        source env/bin/activate
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        source env/bin/activate
        flake8 .
    - name: Test with pytest
      run: |
        source env/bin/activate
        pytest
    - name: Run script and Generate Report
      run: |
        source env/bin/activate
        python3 describe_statistics.py  # Replace with your actual script name
