name: Python CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Set up Virtual Environment
      run: make setup
    - name: Install Dependencies
      run: make install
    - name: Lint with pylint
      run: make lint
    - name: Check format
      run: make format
    - name: Test with pytest
      run: make test
    - name: Run script and Generate Report
      run: make run
